export const enum HttpStatusCode {
  _100_CONTINUE = 100,
  _101_SWITCHING_PROTOCOLS = 101,
  _102_PROCESSING = 102,

  _200_OK = 200,
  _201_CREATED = 201,
  _202_ACCEPTED = 202,
  _203_NON_AUTHORITATIVE_INFORMATION = 203,
  _204_NO_CONTENT = 204,
  _205_RESET_CONTENT = 205,
  _206_PARTIAL_CONTENT = 206,

  _300_AMBIGUOUS = 300,
  _301_MOVED_PERMANENTLY = 301,
  _302_FOUND = 302,
  _303_SEE_OTHER = 303,
  _304_NOT_MODIFIED = 304,
  _307_TEMPORARY_REDIRECT = 307,
  _308_PERMANENT_REDIRECT = 308,

  _400_BAD_REQUEST = 400,
  _401_UNAUTHORIZED = 401,
  _402_PAYMENT_REQUIRED = 402,
  _403_FORBIDDEN = 403,
  _404_NOT_FOUND = 404,
  _405_METHOD_NOT_ALLOWED = 405,
  _406_NOT_ACCEPTABLE = 406,
  _407_PROXY_AUTHENTICATION_REQUIRED = 407,
  _408_REQUEST_TIMEOUT = 408,
  _409_CONFLICT = 409,
  _410_GONE = 410,
  _411_LENGTH_REQUIRED = 411,
  _412_PRECONDITION_FAILED = 412,
  _413_PAYLOAD_TOO_LARGE = 413,
  _414_URI_TOO_LONG = 414,
  _415_UNSUPPORTED_MEDIA_TYPE = 415,
  _416_REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  _417_EXPECTATION_FAILED = 417,
  _418_I_AM_A_TEAPOT = 418,
  _422_UNPROCESSABLE_ENTITY = 422,
  _424_FAILED_DEPENDENCY = 424,
  _429_TOO_MANY_REQUESTS = 429,

  _500_INTERNAL_SERVER_ERROR = 500,
  _501_NOT_IMPLEMENTED = 501,
  _502_BAD_GATEWAY = 502,
  _503_SERVICE_UNAVAILABLE = 503,
  _504_GATEWAY_TIMEOUT = 504,
  _505_HTTP_VERSION_NOT_SUPPORTED = 505,
  _506_VARIANT_ALSO_NEGOTIATES = 506,
  _507_INSUFFICIENT_STORAGE = 507,
  _508_LOOP_DETECTED = 508,
  _509_BANDWIDTH_LIMIT_EXCEEDED = 509,
  _510_NOT_EXTENDED = 510,
  _511_NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export enum HttpStatus {
  _100_CONTINUE = "Continue",
  _101_SWITCHING_PROTOCOLS = "Switching Protocols",
  _102_PROCESSING = "Processing",
  CHECKPOINT = "Checkpoint",

  // 2xx Success
  _200_OK = "OK",
  _201_CREATED_201 = "Created",
  _202_ACCEPTED = "Accepted",
  _203_NON_AUTHORITATIVE_INFORMATION = "Non-Authoritative Information",
  _204_NO_CONTENT = "No Content",
  _205_RESET_CONTENT = "Reset Content",
  _206_PARTIAL_CONTENT = "Partial Content",
  MULTI_STATUS = "Multi-Status",
  ALREADY_REPORTED = "Already Reported",
  IM_USED = "IM Used",

  // 3xx Redirection
  MULTIPLE_CHOICES = "Multiple Choices",
  _301_MOVED_PERMANENTLY = "Moved Permanently",
  _302_FOUND = "Found",
  MOVED_TEMPORARILY = "Moved Temporarily",
  _303_SEE_OTHER = "See Other",
  _304_NOT_MODIFIED = "Not Modified",
  USE_PROXY = "Use Proxy",
  _307_TEMPORARY_REDIRECT = "Temporary Redirect",
  __308_PERMANENT_REDIRECT = "Permanent Redirect",

  // --- 4xx Client Error ---
  _400_BAD_REQUEST = "Bad Request",
  _401_UNAUTHORIZED = "Unauthorized",
  _402_PAYMENT_REQUIRED = "Payment Required",
  _403_FORBIDDEN = "Forbidden",
  _404_NOT_FOUND = "Not Found",
  _405_METHOD_NOT_ALLOWED = "Method Not Allowed",
  _406_NOT_ACCEPTABLE = "Not Acceptable",
  _407_PROXY_AUTHENTICATION_REQUIRED = "Proxy Authentication Required",
  _408_REQUEST_TIMEOUT = "Request Timeout",
  _409_CONFLICT = "Conflict",
  _410_GONE = "Gone",
  _411_LENGTH_REQUIRED = "Length Required",
  _412_PRECONDITION_FAILED = "Precondition Failed",
  _413_PAYLOAD_TOO_LARGE = "Payload Too Large",
  REQUEST_ENTITY_TOO_LARGE = "Request Entity Too Large",
  _414_URI_TOO_LONG = "URI Too Long",
  REQUEST_URI_TOO_LONG = "Request-URI Too Long",
  _415_UNSUPPORTED_MEDIA_TYPE = "Unsupported Media Type",
  _416_REQUESTED_RANGE_NOT_SATISFIABLE = "Requested range not satisfiable",
  _417_EXPECTATION_FAILED = "Expectation Failed",
  _418_I_AM_A_TEAPOT = "I'm a teapot",
  INSUFFICIENT_SPACE_ON_RESOURCE = "Insufficient Space On Resource",
  METHOD_FAILURE = "Method Failure",
  DESTINATION_LOCKED = "Destination Locked",
  _422_UNPROCESSABLE_ENTITY = "Unprocessable Entity",
  LOCKED = "Locked",
  _424_FAILED_DEPENDENCY = "Failed Dependency",
  UPGRADE_REQUIRED = "Upgrade Required",
  PRECONDITION_REQUIRED = "Precondition Required",
  _429_TOO_MANY_REQUESTS = "Too Many Requests",
  REQUEST_HEADER_FIELDS_TOO_LARGE = "Request Header Fields Too Large",
  UNAVAILABLE_FOR_LEGAL_REASONS = "Unavailable For Legal Reasons",

  // --- 5xx Server Error ---
  _500_INTERNAL_SERVER_ERROR = "Internal Server Error",
  _501_NOT_IMPLEMENTED = "Not Implemented",
  _502_BAD_GATEWAY = "Bad Gateway",
  _503_SERVICE_UNAVAILABLE = "Service Unavailable",
  _504_GATEWAY_TIMEOUT = "Gateway Timeout",
  _505_HTTP_VERSION_NOT_SUPPORTED = "HTTP Version not supported",
  _506_VARIANT_ALSO_NEGOTIATES = "Variant Also Negotiates",
  _507_INSUFFICIENT_STORAGE = "Insufficient Storage",
  _508_LOOP_DETECTED = "Loop Detected",
  _509_BANDWIDTH_LIMIT_EXCEEDED = "Bandwidth Limit Exceeded",
  _510_NOT_EXTENDED = "Not Extended",
}
